package com.ralf.module_db.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ralf.module_db.data.entity.ContractDBEntity;
import com.ralf.module_db.data.entity.SampleDBEntity;

import com.ralf.module_db.db.ContractDBEntityDao;
import com.ralf.module_db.db.SampleDBEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contractDBEntityDaoConfig;
    private final DaoConfig sampleDBEntityDaoConfig;

    private final ContractDBEntityDao contractDBEntityDao;
    private final SampleDBEntityDao sampleDBEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contractDBEntityDaoConfig = daoConfigMap.get(ContractDBEntityDao.class).clone();
        contractDBEntityDaoConfig.initIdentityScope(type);

        sampleDBEntityDaoConfig = daoConfigMap.get(SampleDBEntityDao.class).clone();
        sampleDBEntityDaoConfig.initIdentityScope(type);

        contractDBEntityDao = new ContractDBEntityDao(contractDBEntityDaoConfig, this);
        sampleDBEntityDao = new SampleDBEntityDao(sampleDBEntityDaoConfig, this);

        registerDao(ContractDBEntity.class, contractDBEntityDao);
        registerDao(SampleDBEntity.class, sampleDBEntityDao);
    }
    
    public void clear() {
        contractDBEntityDaoConfig.clearIdentityScope();
        sampleDBEntityDaoConfig.clearIdentityScope();
    }

    public ContractDBEntityDao getContractDBEntityDao() {
        return contractDBEntityDao;
    }

    public SampleDBEntityDao getSampleDBEntityDao() {
        return sampleDBEntityDao;
    }

}
