package com.ralf.module_db.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ralf.module_db.data.entity.SampleDBEntity;
import com.ralf.module_db.data.entity.PetEntity;
import com.ralf.module_db.data.entity.MessageRemindEntity;

import com.ralf.module_db.db.SampleDBEntityDao;
import com.ralf.module_db.db.PetEntityDao;
import com.ralf.module_db.db.MessageRemindEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sampleDBEntityDaoConfig;
    private final DaoConfig petEntityDaoConfig;
    private final DaoConfig messageRemindEntityDaoConfig;

    private final SampleDBEntityDao sampleDBEntityDao;
    private final PetEntityDao petEntityDao;
    private final MessageRemindEntityDao messageRemindEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sampleDBEntityDaoConfig = daoConfigMap.get(SampleDBEntityDao.class).clone();
        sampleDBEntityDaoConfig.initIdentityScope(type);

        petEntityDaoConfig = daoConfigMap.get(PetEntityDao.class).clone();
        petEntityDaoConfig.initIdentityScope(type);

        messageRemindEntityDaoConfig = daoConfigMap.get(MessageRemindEntityDao.class).clone();
        messageRemindEntityDaoConfig.initIdentityScope(type);

        sampleDBEntityDao = new SampleDBEntityDao(sampleDBEntityDaoConfig, this);
        petEntityDao = new PetEntityDao(petEntityDaoConfig, this);
        messageRemindEntityDao = new MessageRemindEntityDao(messageRemindEntityDaoConfig, this);

        registerDao(SampleDBEntity.class, sampleDBEntityDao);
        registerDao(PetEntity.class, petEntityDao);
        registerDao(MessageRemindEntity.class, messageRemindEntityDao);
    }
    
    public void clear() {
        sampleDBEntityDaoConfig.clearIdentityScope();
        petEntityDaoConfig.clearIdentityScope();
        messageRemindEntityDaoConfig.clearIdentityScope();
    }

    public SampleDBEntityDao getSampleDBEntityDao() {
        return sampleDBEntityDao;
    }

    public PetEntityDao getPetEntityDao() {
        return petEntityDao;
    }

    public MessageRemindEntityDao getMessageRemindEntityDao() {
        return messageRemindEntityDao;
    }

}
