package com.ralf.module_db.db;

import com.ralf.module_db.data.entity.MessageRemindEntity;
import com.ralf.module_db.data.entity.PetAssistantEntity;
import com.ralf.module_db.data.entity.PetEntity;
import com.ralf.module_db.data.entity.SampleDBEntity;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageRemindEntityDaoConfig;
    private final DaoConfig petAssistantEntityDaoConfig;
    private final DaoConfig sampleDBEntityDaoConfig;
    private final DaoConfig petEntityDaoConfig;

    private final MessageRemindEntityDao messageRemindEntityDao;
    private final PetAssistantEntityDao petAssistantEntityDao;
    private final SampleDBEntityDao sampleDBEntityDao;
    private final PetEntityDao petEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageRemindEntityDaoConfig = daoConfigMap.get(MessageRemindEntityDao.class).clone();
        messageRemindEntityDaoConfig.initIdentityScope(type);

        petAssistantEntityDaoConfig = daoConfigMap.get(PetAssistantEntityDao.class).clone();
        petAssistantEntityDaoConfig.initIdentityScope(type);

        sampleDBEntityDaoConfig = daoConfigMap.get(SampleDBEntityDao.class).clone();
        sampleDBEntityDaoConfig.initIdentityScope(type);

        petEntityDaoConfig = daoConfigMap.get(PetEntityDao.class).clone();
        petEntityDaoConfig.initIdentityScope(type);

        messageRemindEntityDao = new MessageRemindEntityDao(messageRemindEntityDaoConfig, this);
        petAssistantEntityDao = new PetAssistantEntityDao(petAssistantEntityDaoConfig, this);
        sampleDBEntityDao = new SampleDBEntityDao(sampleDBEntityDaoConfig, this);
        petEntityDao = new PetEntityDao(petEntityDaoConfig, this);

        registerDao(MessageRemindEntity.class, messageRemindEntityDao);
        registerDao(PetAssistantEntity.class, petAssistantEntityDao);
        registerDao(SampleDBEntity.class, sampleDBEntityDao);
        registerDao(PetEntity.class, petEntityDao);
    }
    
    public void clear() {
        messageRemindEntityDaoConfig.clearIdentityScope();
        petAssistantEntityDaoConfig.clearIdentityScope();
        sampleDBEntityDaoConfig.clearIdentityScope();
        petEntityDaoConfig.clearIdentityScope();
    }

    public MessageRemindEntityDao getMessageRemindEntityDao() {
        return messageRemindEntityDao;
    }

    public PetAssistantEntityDao getPetAssistantEntityDao() {
        return petAssistantEntityDao;
    }

    public SampleDBEntityDao getSampleDBEntityDao() {
        return sampleDBEntityDao;
    }

    public PetEntityDao getPetEntityDao() {
        return petEntityDao;
    }

}
